version: '3'
services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - .:/var/www
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    links:
      - mysql

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
    depends_on:
      - php-fpm
    ports:
      - ${NGINX_PORT}:80

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
