version: '3'
services:
  php-fpm:
    image: php:5.5-fpm
    volumes:
      - .:/var/www

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
    depends_on:
      - php-fpm
    env_file:
      - .env
    ports:
      - ${NGINX_PORT}:80

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=phonebook
      - MYSQL_USER=phonebook
      - MYSQL_PASSWORD=root
